// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: services.proto

package servicespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdRequest) Reset() {
	*x = IdRequest{}
	mi := &file_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdRequest) ProtoMessage() {}

func (x *IdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdRequest.ProtoReflect.Descriptor instead.
func (*IdRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{0}
}

func (x *IdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{1}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TitleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TitleRequest) Reset() {
	*x = TitleRequest{}
	mi := &file_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleRequest) ProtoMessage() {}

func (x *TitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleRequest.ProtoReflect.Descriptor instead.
func (*TitleRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{2}
}

func (x *TitleRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{3}
}

func (x *ClientRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ClientRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ClientRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type FavoriteMovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	MovieId       int32                  `protobuf:"varint,2,opt,name=movieId,proto3" json:"movieId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FavoriteMovieRequest) Reset() {
	*x = FavoriteMovieRequest{}
	mi := &file_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavoriteMovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavoriteMovieRequest) ProtoMessage() {}

func (x *FavoriteMovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavoriteMovieRequest.ProtoReflect.Descriptor instead.
func (*FavoriteMovieRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{4}
}

func (x *FavoriteMovieRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *FavoriteMovieRequest) GetMovieId() int32 {
	if x != nil {
		return x.MovieId
	}
	return 0
}

type MovieRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieRequest) Reset() {
	*x = MovieRequest{}
	mi := &file_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieRequest) ProtoMessage() {}

func (x *MovieRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieRequest.ProtoReflect.Descriptor instead.
func (*MovieRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{5}
}

func (x *MovieRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{6}
}

func (x *ClientResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ClientResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ClientResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type MovieResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MovieResponse) Reset() {
	*x = MovieResponse{}
	mi := &file_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MovieResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieResponse) ProtoMessage() {}

func (x *MovieResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieResponse.ProtoReflect.Descriptor instead.
func (*MovieResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{7}
}

func (x *MovieResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MovieResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieResponse) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type IsExistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exist         bool                   `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsExistResponse) Reset() {
	*x = IsExistResponse{}
	mi := &file_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsExistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsExistResponse) ProtoMessage() {}

func (x *IsExistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsExistResponse.ProtoReflect.Descriptor instead.
func (*IsExistResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{8}
}

func (x *IsExistResponse) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_services_proto_rawDescGZIP(), []int{10}
}

var File_services_proto protoreflect.FileDescriptor

const file_services_proto_rawDesc = "" +
	"\n" +
	"\x0eservices.proto\x12\bservices\"\x1b\n" +
	"\tIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"$\n" +
	"\fTitleRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"o\n" +
	"\rClientRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"L\n" +
	"\x14FavoriteMovieRequest\x12\x1a\n" +
	"\bclientId\x18\x01 \x01(\x05R\bclientId\x12\x18\n" +
	"\amovieId\x18\x02 \x01(\x05R\amovieId\"J\n" +
	"\fMovieRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\"p\n" +
	"\x0eClientResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"K\n" +
	"\rMovieResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\"'\n" +
	"\x0fIsExistResponse\x12\x14\n" +
	"\x05exist\x18\x01 \x01(\bR\x05exist\"*\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x0e\n" +
	"\fEmptyRequest2\xe5\x03\n" +
	"\x12ClientProtoService\x12>\n" +
	"\rGetClientById\x12\x13.services.IdRequest\x1a\x18.services.ClientResponse\x12D\n" +
	"\x10GetClientByEmail\x12\x16.services.EmailRequest\x1a\x18.services.ClientResponse\x12B\n" +
	"\rIsClientExist\x12\x16.services.EmailRequest\x1a\x19.services.IsExistResponse\x12>\n" +
	"\tAddClient\x12\x17.services.ClientRequest\x1a\x18.services.ClientResponse\x12A\n" +
	"\fUpdateClient\x12\x17.services.ClientRequest\x1a\x18.services.ClientResponse\x12=\n" +
	"\fDeleteClient\x12\x13.services.IdRequest\x1a\x18.services.StatusResponse\x12C\n" +
	"\rGetAllClients\x12\x16.services.EmptyRequest\x1a\x18.services.ClientResponse0\x012\xd3\x03\n" +
	"\x11MovieProtoService\x12<\n" +
	"\fGetMovieById\x12\x13.services.IdRequest\x1a\x17.services.MovieResponse\x12B\n" +
	"\x0fGetMovieByTitle\x12\x16.services.TitleRequest\x1a\x17.services.MovieResponse\x12>\n" +
	"\fIsMovieExist\x12\x13.services.IdRequest\x1a\x19.services.IsExistResponse\x12;\n" +
	"\bAddMovie\x12\x16.services.MovieRequest\x1a\x17.services.MovieResponse\x12>\n" +
	"\vUpdateMovie\x12\x16.services.MovieRequest\x1a\x17.services.MovieResponse\x12<\n" +
	"\vDeleteMovie\x12\x13.services.IdRequest\x1a\x18.services.StatusResponse\x12A\n" +
	"\fGetAllMovies\x12\x16.services.EmptyRequest\x1a\x17.services.MovieResponse0\x012\x91\x02\n" +
	"\x19FavoriteMovieProtoService\x12R\n" +
	"\x16AddClientFavoriteMovie\x12\x1e.services.FavoriteMovieRequest\x1a\x18.services.StatusResponse\x12I\n" +
	"\x17GetClientFavoriteMovies\x12\x13.services.IdRequest\x1a\x17.services.MovieResponse0\x01\x12U\n" +
	"\x19RemoveClientFavoriteMovie\x12\x1e.services.FavoriteMovieRequest\x1a\x18.services.StatusResponseB\x0eZ\f./servicespbb\x06proto3"

var (
	file_services_proto_rawDescOnce sync.Once
	file_services_proto_rawDescData []byte
)

func file_services_proto_rawDescGZIP() []byte {
	file_services_proto_rawDescOnce.Do(func() {
		file_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)))
	})
	return file_services_proto_rawDescData
}

var file_services_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_services_proto_goTypes = []any{
	(*IdRequest)(nil),            // 0: services.IdRequest
	(*EmailRequest)(nil),         // 1: services.EmailRequest
	(*TitleRequest)(nil),         // 2: services.TitleRequest
	(*ClientRequest)(nil),        // 3: services.ClientRequest
	(*FavoriteMovieRequest)(nil), // 4: services.FavoriteMovieRequest
	(*MovieRequest)(nil),         // 5: services.MovieRequest
	(*ClientResponse)(nil),       // 6: services.ClientResponse
	(*MovieResponse)(nil),        // 7: services.MovieResponse
	(*IsExistResponse)(nil),      // 8: services.IsExistResponse
	(*StatusResponse)(nil),       // 9: services.StatusResponse
	(*EmptyRequest)(nil),         // 10: services.EmptyRequest
}
var file_services_proto_depIdxs = []int32{
	0,  // 0: services.ClientProtoService.GetClientById:input_type -> services.IdRequest
	1,  // 1: services.ClientProtoService.GetClientByEmail:input_type -> services.EmailRequest
	1,  // 2: services.ClientProtoService.IsClientExist:input_type -> services.EmailRequest
	3,  // 3: services.ClientProtoService.AddClient:input_type -> services.ClientRequest
	3,  // 4: services.ClientProtoService.UpdateClient:input_type -> services.ClientRequest
	0,  // 5: services.ClientProtoService.DeleteClient:input_type -> services.IdRequest
	10, // 6: services.ClientProtoService.GetAllClients:input_type -> services.EmptyRequest
	0,  // 7: services.MovieProtoService.GetMovieById:input_type -> services.IdRequest
	2,  // 8: services.MovieProtoService.GetMovieByTitle:input_type -> services.TitleRequest
	0,  // 9: services.MovieProtoService.IsMovieExist:input_type -> services.IdRequest
	5,  // 10: services.MovieProtoService.AddMovie:input_type -> services.MovieRequest
	5,  // 11: services.MovieProtoService.UpdateMovie:input_type -> services.MovieRequest
	0,  // 12: services.MovieProtoService.DeleteMovie:input_type -> services.IdRequest
	10, // 13: services.MovieProtoService.GetAllMovies:input_type -> services.EmptyRequest
	4,  // 14: services.FavoriteMovieProtoService.AddClientFavoriteMovie:input_type -> services.FavoriteMovieRequest
	0,  // 15: services.FavoriteMovieProtoService.GetClientFavoriteMovies:input_type -> services.IdRequest
	4,  // 16: services.FavoriteMovieProtoService.RemoveClientFavoriteMovie:input_type -> services.FavoriteMovieRequest
	6,  // 17: services.ClientProtoService.GetClientById:output_type -> services.ClientResponse
	6,  // 18: services.ClientProtoService.GetClientByEmail:output_type -> services.ClientResponse
	8,  // 19: services.ClientProtoService.IsClientExist:output_type -> services.IsExistResponse
	6,  // 20: services.ClientProtoService.AddClient:output_type -> services.ClientResponse
	6,  // 21: services.ClientProtoService.UpdateClient:output_type -> services.ClientResponse
	9,  // 22: services.ClientProtoService.DeleteClient:output_type -> services.StatusResponse
	6,  // 23: services.ClientProtoService.GetAllClients:output_type -> services.ClientResponse
	7,  // 24: services.MovieProtoService.GetMovieById:output_type -> services.MovieResponse
	7,  // 25: services.MovieProtoService.GetMovieByTitle:output_type -> services.MovieResponse
	8,  // 26: services.MovieProtoService.IsMovieExist:output_type -> services.IsExistResponse
	7,  // 27: services.MovieProtoService.AddMovie:output_type -> services.MovieResponse
	7,  // 28: services.MovieProtoService.UpdateMovie:output_type -> services.MovieResponse
	9,  // 29: services.MovieProtoService.DeleteMovie:output_type -> services.StatusResponse
	7,  // 30: services.MovieProtoService.GetAllMovies:output_type -> services.MovieResponse
	9,  // 31: services.FavoriteMovieProtoService.AddClientFavoriteMovie:output_type -> services.StatusResponse
	7,  // 32: services.FavoriteMovieProtoService.GetClientFavoriteMovies:output_type -> services.MovieResponse
	9,  // 33: services.FavoriteMovieProtoService.RemoveClientFavoriteMovie:output_type -> services.StatusResponse
	17, // [17:34] is the sub-list for method output_type
	0,  // [0:17] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_services_proto_init() }
func file_services_proto_init() {
	if File_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_proto_rawDesc), len(file_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_services_proto_goTypes,
		DependencyIndexes: file_services_proto_depIdxs,
		MessageInfos:      file_services_proto_msgTypes,
	}.Build()
	File_services_proto = out.File
	file_services_proto_goTypes = nil
	file_services_proto_depIdxs = nil
}
